version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always
    volumes:
      - .:/var/www/html/wp-content/plugins/rezfusion-components
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
