version: '3.1'
services:
  wordpress:
    image: ${WP_BASE_IMAGE}
    restart: always
    volumes:
      - .:/var/www/html/wp-content/plugins/rezfusion-components
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root
      BLUEPRINT_ENVIRONMENT: ${BLUEPRINT_ENVIRONMENT}
      BLUEPRINT_CHANNEL: ${BLUEPRINT_CHANNEL}
      BLUEPRINT_URL: ${BLUEPRINT_URL}
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 33070:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
