version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-plugin:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            sh $(pwd)/bin/build.sh
            sh $(pwd)/bin/test.sh
      - store_artifacts:
          path: build/coverage-report
      - store_test_results:
          path: build
  test-js:
    executor:
       name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install npm dependencies
                command: npm ci
            - run:
                name: Verify `npm build`
                command: npm run build
            - run:
                name: Verify `npm build:admin`
                command: npm run build:admin
            - run:
                name: Execute Tests
                command: npm test
workflows:
  test:
    jobs:
      - test-plugin
      - test-js
