name: Build, test and release

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build_test_and_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      WP_BASE_IMAGE: rzfwp:latest
      BLUEPRINT_CHANNEL: "-"
      BLUEPRINT_URL: https://assets.rezfusion.com/bluetent/channels/httpswwwrezfusionhubdemocom/bundle.js
      BLUEPRINT_ENVIRONMENT: prd
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Environment variables check
        run: ./bin/environment-variables-check.sh

      - name: Setup
        run: |
          mkdir ./node_modules/
          rm -rf dist/*
          chmod -R 777 `pwd`

      - name: Wordpress and database Docker containers build
        run: ./bin/build.sh

      - name: PHP tests
        run: ./bin/test.sh

      - name: Clean dist directory
        run: |
          rm -rf dist/*
          chmod 777 dist/

      - name: Build components
        run: ./bin/build-components.sh

      - name: Remove dev Composer packages
        run: docker-compose exec -T wordpress bash -c "cd /var/www/html/wp-content/plugins/rezfusion-components && composer install --no-dev"

      - name: Semantic release
        run: npx semantic-release
